[package]
name = "membrane"
version = "0.1.0"
authors = ["trix"]
edition = "2018"

[dependencies]
osmosis-std = { version = "0.12.0" }
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
cosmwasm-storage = "1.0.0"
prost = "0.11"
prost-types = "0.11"
bigint = "4"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
cw20 = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }


