[package]
name = "membrane"
version = "0.1.0"
authors = ["Membrane Devs"]
edition = "2018"

[dependencies]
cw-dex-router = "0.1.0"
apollo-cw-asset = "0.1.0"
cw-dex = { version = "0.1.3", features = ["osmosis"] }
osmosis-std = { version = "0.15.2" }
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
cosmwasm-schema = "1.1.0"
cw-coins = "0.6.1"
pyth-sdk-cw = "1.0.0"
cosmwasm-storage = "1.0.0"
prost = "0.11"
prost-types = "0.11"
uint = "0.8"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }


