name: Artifacts

on:
  push:
    branches:
      - master
      - main
      - oracle_pricing
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:

  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Compile contracts to wasm
        run: |
          docker run --rm -v "$(pwd)":/code \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            cosmwasm/workspace-optimizer:0.14.0 --no-locked

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/
