name: Artifacts

on:
  push:
    branches:
      - master
      - main
      - oracle_pricing
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:

  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build contracts
        run: |
          for contract in contracts/*; do
            if [ -d "$contract" ]; then
              echo "Building $contract..."
              cd $contract
              cargo build --release --target wasm32-unknown-unknown
              cd ../..
            fi
          done

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Optimize and collect wasm files
        run: |
          for contract in contracts/*; do
            if [ -d "$contract" ]; then
              name=$(basename $contract)
              wasm-opt -Oz target/wasm32-unknown-unknown/release/$name.wasm -o artifacts/$name.wasm
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/
